FULL_SCREEN = "FULL_SCREEN"
MOVE_UP = "MOVE_UP"
MOVE_LEFT = "MOVE_LEFT"
MOVE_RIGHT = "MOVE_RIGHT"
MOVE_DOWN = "MOVE_DOWN"
ATTACK = "ATTACK"
INVENTORY = "INVENTORY"

MOVEMENT_ACTION = [
    MOVE_DOWN,
    MOVE_UP,
    MOVE_RIGHT,
    MOVE_LEFT,
]